document.writeln("<!--copyright-->");
document.writeln("  <footer>");
document.writeln("    <div class=\'footer-outer\'>");
document.writeln("      <div class=\'footer-left\'>");
document.writeln("        <div class=\'ican-logo\'>");
document.writeln("          <img src=\'images/ican.png\' alt=\'艾肯娛樂\'>");
document.writeln("        </div>");
document.writeln("        <div class=\'all-right\'>©<span>iCan</span>Entertainment Co.,Ltd. All Rights Reserved.</div>");
document.writeln("      </div>");
document.writeln("      <div class=\'logos\'>");
document.writeln("        <img src=\'images/logos.png\' alt=\'享樂時光\'>");
document.writeln("      </div>");
document.writeln("      <div class=\'footer-right\'>");
document.writeln("        <div class=\'classLevel\'>");
document.writeln("          <img src=\'images/15+.jpg\' alt=\'15+\'>");
document.writeln("        </div>");
document.writeln("        <div class=\'classTxt\'>");
document.writeln("              ◆ 本遊戲部分內容涉及暴力、菸酒、戀愛交友、性，依遊戲軟體分級管理辦法分類為輔15級。");
document.writeln("          <br>◆ 注意使用時間，請避免沉迷遊戲。");
document.writeln("          <br>◆ 遊戲部分內容需另外支付費用。");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("  </footer>");