document.writeln("	<link rel=\'stylesheet\' href=\'css/header.css\'>");

document.writeln("<div id=\'topBar\'>");
document.writeln("		<a href=\'https://www.icantw.com/\' title=\'ican艾肯娛樂\' target=\'_blank\'>");
document.writeln("			<img class=\'logo\' src=\'images/logo.png\'>");
document.writeln("		</a>");
document.writeln("		<a class=\'hamburger\' href=\'javascript:void(0);\'>");
document.writeln("			<div></div>");
document.writeln("			<div></div>");
document.writeln("			<div></div>");
document.writeln("		</a>");
document.writeln("		<div class=\'icon-link\'>");
document.writeln("			<a href=\'https://www.icantw.com/\' title=\'艾肯平台\' target=\'_blank\'>");
document.writeln("				<i class=\'fas fa-home\'></i>");
document.writeln("				<span>艾肯平台</span>");
document.writeln("			</a>");
document.writeln("			<a href=\'https://www.facebook.com/icantw.TY\' title=\'遊戲粉絲團\' target=\'_blank\'>");
document.writeln("				<i class=\'fab fa-facebook-square\'></i>");
document.writeln("				<span>粉絲團</span>");
document.writeln("			</a>");
document.writeln("			<a href=\'https://passport.icantw.com/payment\' title=\'網頁儲值\' target=\'_blank\'>");
document.writeln("				<i class=\'fas fa-donate\'></i>");
document.writeln("				<span>網頁儲值</span>");
document.writeln("			</a>");
document.writeln("		</div>");
document.writeln("	</div>");